packageName: "sense-export"
wbfolder:
  enabled: false
import:
  files:
    - ["./node_modules/sense-extension-utils/dist/extUtils.js", "./.tmp/lib/external/sense-extension-utils"]
    - ["./node_modules/sense-angular-directives/dist/eui-simple-table/eui-simple-table.js", "./.tmp/lib/components/eui-simple-table"]
    - ["./node_modules/sense-angular-directives/dist/eui-simple-table/eui-simple-table.css", "./.tmp/lib/components/eui-simple-table"]
    - ["./node_modules/sense-angular-directives/dist/eui-simple-table/eui-simple-table.ng.html", "./.tmp/lib/components/eui-simple-table"]
    - ["./node_modules/sense-angular-directives/dist/eui-overlay/eui-overlay.js", "./.tmp/lib/components/eui-overlay"]
    - ["./node_modules/sense-angular-directives/dist/eui-overlay/eui-overlay.css", "./.tmp/lib/components/eui-overlay"]
deployment:
  toSsh:
    enabled: true
    host: "192.168.56.13"
    port: 22
    username: "stefanwalther"
    password: "Test1234"
    dest: "/cygdrive/c/Users/stefanwalther/Documents/Qlik/Sense/Extensions/qssample-property-array"
