packageName: "sense-export"
wbfolder:
  enabled: false
import:
  fromLocal:
    files:
      - ["./node_modules/sense-extension-utils/dist/general-utils.js", "./.tmp/lib/external/sense-extension-utils"]
      - ["./node_modules/sense-angular-directives/dist/eui-simple-table/eui-simple-table.js", "./.tmp/lib/components/eui-simple-table"]
      - ["./node_modules/sense-angular-directives/dist/eui-simple-table/eui-simple-table.css", "./.tmp/lib/components/eui-simple-table"]
      - ["./node_modules/sense-angular-directives/dist/eui-simple-table/eui-simple-table.ng.html", "./.tmp/lib/components/eui-simple-table"]
      - ["./node_modules/sense-angular-directives/dist/eui-overlay/eui-overlay.js", "./.tmp/lib/components/eui-overlay"]
      - ["./node_modules/sense-angular-directives/dist/eui-overlay/eui-overlay.css", "./.tmp/lib/components/eui-overlay"]
